# Generated by scripts/update-homebrew.sh. Do not edit by hand.
class Vpndetection < Formula
  desc "Official CLI for the VPNDetection API"
  homepage "https://vpndetection.io"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/vpndetection-io/cli/releases/download/v1.0.0/vpndetection_1.0.0_darwin_arm64.tar.gz"
      sha256 "3223995783de98eae15506af5d06cc4c413d256476d203ef72546d03db1763f5"
    end
    on_intel do
      url "https://github.com/vpndetection-io/cli/releases/download/v1.0.0/vpndetection_1.0.0_darwin_amd64.tar.gz"
      sha256 "5a70c88389a68510dc0e498194f2edd3bd034301b7137cd1502008adfea36b9c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vpndetection-io/cli/releases/download/v1.0.0/vpndetection_1.0.0_linux_arm64.tar.gz"
      sha256 "ea6123db375e391c40a778b2b271ec91833737f1310be03e260ee637f149d1ae"
    end
    on_intel do
      url "https://github.com/vpndetection-io/cli/releases/download/v1.0.0/vpndetection_1.0.0_linux_amd64.tar.gz"
      sha256 "154017c71fc3c0dcac97f3964c6eb77f450f67f4ac42d07fbbbcb5013b39c3df"
    end
  end

  def install
    bin.install "vpndetection"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vpndetection version")
  end
end
