# Generated by scripts/update-homebrew.sh. Do not edit by hand.
class Vpndetection < Formula
  desc "Official CLI for the VPNDetection API"
  homepage "https://vpndetection.io"
  version "1.3.6"
  license "MIT"

  on_macos do
    # Go 1.27 builds the release and needs Ventura. Inside on_macos because
    # Homebrew satisfies it only on macOS: at the top level every Linux install fails.
    depends_on macos: :ventura

    on_arm do
      url "https://github.com/vpndetection-io/cli/releases/download/v1.3.6/vpndetection_1.3.6_darwin_arm64.tar.gz"
      sha256 "965ebb81327a5df66cabcbe101b2caee6bf2e7632ea13da05ee5c55d828ddb10"
    end
    on_intel do
      url "https://github.com/vpndetection-io/cli/releases/download/v1.3.6/vpndetection_1.3.6_darwin_amd64.tar.gz"
      sha256 "3a600c4262213ddff9b60d4b0a738cef07a5e0a6695956c6a5d30aa156813c1e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vpndetection-io/cli/releases/download/v1.3.6/vpndetection_1.3.6_linux_arm64.tar.gz"
      sha256 "57f55d878824f0286bf03b90961a5978205225a36145883908dea9123c5445c5"
    end
    on_intel do
      url "https://github.com/vpndetection-io/cli/releases/download/v1.3.6/vpndetection_1.3.6_linux_amd64.tar.gz"
      sha256 "194a777e4b4f60b0a2ffbcd4bf0d8795ec10797b513d082fad4e0a47e7db0ffc"
    end
  end

  def install
    bin.install "vpndetection"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vpndetection version")
  end
end
