# Generated by scripts/update-homebrew.sh. Do not edit by hand.
class Vpndetection < Formula
  desc "Official CLI for the VPNDetection API"
  homepage "https://vpndetection.io"
  version "1.3.1"
  license "MIT"

  on_macos do
    # Go 1.27 builds the release and needs Ventura. Inside on_macos because
    # Homebrew satisfies it only on macOS: at the top level every Linux install fails.
    depends_on macos: :ventura

    on_arm do
      url "https://github.com/vpndetection-io/cli/releases/download/v1.3.1/vpndetection_1.3.1_darwin_arm64.tar.gz"
      sha256 "00aff8fe24258ccfd04c27e0e30afcb6d6da0e84d697ac7b0216dffb70395d72"
    end
    on_intel do
      url "https://github.com/vpndetection-io/cli/releases/download/v1.3.1/vpndetection_1.3.1_darwin_amd64.tar.gz"
      sha256 "18701a6736014ef0f16cc96218f94067eccc23f0b9935318e512e08c99e91234"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vpndetection-io/cli/releases/download/v1.3.1/vpndetection_1.3.1_linux_arm64.tar.gz"
      sha256 "d898dd26214cea814d276a9e00a1964543866bf4ccd122d74d469800f0f5c831"
    end
    on_intel do
      url "https://github.com/vpndetection-io/cli/releases/download/v1.3.1/vpndetection_1.3.1_linux_amd64.tar.gz"
      sha256 "90dc4c6f13ef7139fda1da58d08d2dc6032513bbfd42e72db6c3992e98db3096"
    end
  end

  def install
    bin.install "vpndetection"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vpndetection version")
  end
end
